### PR TITLE
Clear code, add some changes to pad and rename file

### PR DESCRIPTION
**Pull request by softov**
There is my contribution, made some changes to the code and keep commits and credits made by gaboelnuevo

I think its right now.

Please, check for me.

### CODE REVIEW

**Comment by softov** [comment]
Nothing?

**Comment by harveyappleton** [comment]
Yo @softov , brilliant work mate! Just forked from your changes and its so much better. Great stuff.

**Comment by softov** [comment]
tks, do wanna grow it?

Em sex., 15 de mai. de 2020 às 07:59, Harvey Appleton <
notifications@github.com> escreveu:

**Comment by softov** [comment]
@harveyappleton tks, do wanna grow it?

**Pull request merged**
